// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openapi/pkg/models/shared"
)

type PostSearchAppointmentRequest struct {
	// A unique reference used to track the transaction end to end. The recommended format is UUID (a 36-character alphanumeric string "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX").
	APIGWTrackingHeader          string                               `header:"style=simple,explode=false,name=APIGW-Tracking-Header"`
	PostSearchAppointmentRequest *shared.PostSearchAppointmentRequest `request:"mediaType=application/json"`
	// Indicates the product family to which product belongs to.
	//
	ProductFamily shared.ProductFamily `header:"style=simple,explode=false,name=productFamily"`
}

func (o *PostSearchAppointmentRequest) GetAPIGWTrackingHeader() string {
	if o == nil {
		return ""
	}
	return o.APIGWTrackingHeader
}

func (o *PostSearchAppointmentRequest) GetPostSearchAppointmentRequest() *shared.PostSearchAppointmentRequest {
	if o == nil {
		return nil
	}
	return o.PostSearchAppointmentRequest
}

func (o *PostSearchAppointmentRequest) GetProductFamily() shared.ProductFamily {
	if o == nil {
		return shared.ProductFamily("")
	}
	return o.ProductFamily
}

type PostSearchAppointmentResponse struct {
	ContentType string
	Headers     map[string][]string
	StatusCode  int
	RawResponse *http.Response
	// Unauthorized
	//
	// | Code | Message | Description |
	// | ---- | ------- | ----------- |
	// | 40 | Missing credentials | The <i>Authorization</i> parameter is missing. |
	// | 41 | Invalid credentials | The <i>Authorization</i> parameter is not valid. |
	// | 42 | Expired credentials | Renew the access token using the OAuth API and try again. |
	//
	FailureResponse *shared.FailureResponse
	// created
	PostSearchAppointmentResponse *shared.PostSearchAppointmentResponse
	// Bad Request
	//
	// | Code | Message  | Description |
	// | ---- | -------   | ----------- |
	// | 21 | Missing body | This resource requires a body to be provided in the request.|
	// | 25 | Missing header: \<parameter\>| The indicated parameter is missing from the request header. |
	// | 26 | Invalid header value: \<parameter\> | The indicated parameter in the request header is not recognized. |
	// | SiteVisitReasonNotSuported | - |  The error originated from target, when passed <i>siteVisitReason</i> not allowed for the specified product. |
	// | SimNotSupported | - | The error originated from target, when invalid <i>productCode & simProvide</i> flag combination. |
	// | MissingLocationIdentifier | - | The error originated from target, when neither <i>DirectoryNumber</i> nor address supplied.|
	// | TooManyLocationIdentifiers | - |  The error originated from target, when both <i>DirectoryNumber</i> and address supplied. |
	// | TimeSlotNotSupported | - | The error originated from target, when data is valid but we don't support (e.g. ALLDAY) slot for G.Fast.|
	// | AccessLineIdNotRecognised | - | The error originated from target, when  data could not be returned as the access line ID was not recognised.	|
	// | NewExchangeLineNotSupported | - |  The error originated from target, when <i>NewExchangeLine</i> included in appointment request for 'non-SOGEA/SOGFASTline'. |
	// | NoDirectoryNumberForAccessLineId	 | - | The error originated from target, when no installation directory number exists for the given access line ID.|
	// | InvalidInputCombination | - | The error originated from target, when the location identifier, sim flag and product combination is not supported.|
	// | TimeSlotNotAvailable | - |  The error originated from target, when MAC2 2131 the appointment slot you are trying to reserve is no longer available. |
	// | ExchangeLineInactive | - | The error originated from target, when MAC2 2119 appointment cannot be provided for inactive line.	|
	// | MissingCredentials | - | Error from downstream. |
	// | MissingRequestBody |  - | Error from downstream. |
	// | MissingData | - | Error from downstream.|
	// | InvalidData | - | Error from downstream. |
	PostSearchAppointment400ApplicationJSONAnyOf interface{}
	// Forbidden
	//
	// | Code | Message   | Description |
	// | ---- | -------   | ----------- |
	// | 50 | Access denied | The client application is not authorised to call this resource. |
	// | ExchangeLineAssignedToAnotherCP | - | Error from downstream. |
	PostSearchAppointment403ApplicationJSONAnyOf interface{}
	// Unsupported Media Type
	//
	// | Code | Message   | Description |
	// | ---- | -------   | ----------- |
	// | 68 | Unsupported media type | The request body does not match a supported content-type. |
	// | UnsupportedMediaType | - | Error from downstream. |
	PostSearchAppointment415ApplicationJSONAnyOf interface{}
}

func (o *PostSearchAppointmentResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostSearchAppointmentResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *PostSearchAppointmentResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostSearchAppointmentResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PostSearchAppointmentResponse) GetFailureResponse() *shared.FailureResponse {
	if o == nil {
		return nil
	}
	return o.FailureResponse
}

func (o *PostSearchAppointmentResponse) GetPostSearchAppointmentResponse() *shared.PostSearchAppointmentResponse {
	if o == nil {
		return nil
	}
	return o.PostSearchAppointmentResponse
}

func (o *PostSearchAppointmentResponse) GetPostSearchAppointment400ApplicationJSONAnyOf() interface{} {
	if o == nil {
		return nil
	}
	return o.PostSearchAppointment400ApplicationJSONAnyOf
}

func (o *PostSearchAppointmentResponse) GetPostSearchAppointment403ApplicationJSONAnyOf() interface{} {
	if o == nil {
		return nil
	}
	return o.PostSearchAppointment403ApplicationJSONAnyOf
}

func (o *PostSearchAppointmentResponse) GetPostSearchAppointment415ApplicationJSONAnyOf() interface{} {
	if o == nil {
		return nil
	}
	return o.PostSearchAppointment415ApplicationJSONAnyOf
}
