// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type FailureBackendResponse struct {
	// Represents the error code.
	Code string `json:"code"`
	// Represents the error message.
	Reason string `json:"reason"`
}

func (o *FailureBackendResponse) GetCode() string {
	if o == nil {
		return ""
	}
	return o.Code
}

func (o *FailureBackendResponse) GetReason() string {
	if o == nil {
		return ""
	}
	return o.Reason
}
