// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type FailureResponseOptional struct {
	// Represents the error code.
	Code *string `json:"code,omitempty"`
	// Represents the error message.
	Message *string `json:"message,omitempty"`
}

func (o *FailureResponseOptional) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *FailureResponseOptional) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}
